# Generated by Django 6.0.3 on 2026-03-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS-лента'), ('html', 'HTML-страница')], default='rss', max_length=10)),
                ('html_selectors', models.JSONField(blank=True, default=dict)),
                ('source_language', models.CharField(default='ru', max_length=10)),
                ('needs_translation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title_original', models.CharField(blank=True, max_length=500)),
                ('summary_original', models.TextField(blank=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='news/')),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='draft', max_length=15)),
                ('telegram_message_id', models.CharField(blank=True, max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='news.newssource')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
