# Generated by Django 6.0.3 on 2026-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую (фильтр). Пусто = брать всё.', max_length=500),
        ),
    ]
