# Generated by Django 6.0.3 on 2026-03-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_add_keywords_to_newssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='body',
            field=models.TextField(blank=True, help_text='Полный текст статьи (HTML или plain-text)'),
        ),
    ]
