# Generated by Django 6.0.3 on 2026-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_add_body_to_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
