# Generated by Django 6.0.3 on 2026-03-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='body_md',
            field=models.TextField(blank=True, help_text='Редактируйте перевод здесь. HTML в «body» генерируется автоматически при сохранении.', verbose_name='Контент (Markdown)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Если включено — автоматический fetch/перевод не перезапишет контент.', verbose_name='Отредактировано вручную'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=models.TextField(blank=True, help_text='HTML-контент (генерируется из body_md при сохранении)'),
        ),
    ]
