# Generated by Django 6.0.3 on 2026-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_body_md_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=800),
        ),
    ]
