# Generated by Django 6.0.3 on 2026-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_image_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='tag',
            field=models.CharField(blank=True, choices=[('актуально', 'Актуально'), ('интересно', 'Интересно'), ('экономика', 'Экономика'), ('туризм', 'Туризм'), ('политика', 'Политика'), ('спорт', 'Спорт'), ('культура', 'Культура'), ('технологии', 'Технологии')], default='', help_text='Отображается на карточке новости вместо источника.', max_length=20, verbose_name='Тег'),
        ),
    ]
