# Generated by Django 6.0.3 on 2026-03-24 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_allow_unicode_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_md',
            field=models.TextField(blank=True, help_text='Пишите здесь в Markdown. HTML в поле «content» генерируется автоматически.', verbose_name='Контент (Markdown)'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Описание изображения для поисковиков и screen reader', max_length=300, verbose_name='Alt-текст изображения'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ArticleFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog.article')),
            ],
            options={
                'verbose_name': 'FAQ-вопрос',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
    ]
