# Generated by Django 6.0.3 on 2026-03-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_content_md_article_image_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Используйте [imageN] в контенте статьи (N = это число)', verbose_name='Номер')),
                ('image', models.ImageField(upload_to='catalog/article/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, help_text='Описание для SEO и screen-reader', max_length=300, verbose_name='Alt-текст')),
                ('title', models.CharField(blank=True, help_text='Всплывающая подсказка (title="...")', max_length=300, verbose_name='Title')),
                ('caption', models.CharField(blank=True, help_text='Подпись под изображением (figcaption)', max_length=500, verbose_name='Подпись')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='blog.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['number'],
                'unique_together': {('article', 'number')},
            },
        ),
    ]
