# Generated by Django 6.0.3 on 2026-03-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefaq',
            name='is_auto',
            field=models.BooleanField(default=False, help_text='True — создан из #### Q : ... @@ синтаксиса в content_md', verbose_name='Авто (из контента)'),
        ),
    ]
