# Generated by Django 6.0.3 on 2026-03-28 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_faq_is_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-слаг')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slot_type', models.CharField(choices=[('widget_320x480', 'Widget 320x480'), ('widget_300x600', 'Widget 300x600'), ('banner_728x90', 'Banner 728x90'), ('banner_300x250', 'Banner 300x250'), ('text', 'Текстовая ссылка')], max_length=50, verbose_name='Тип слота')),
                ('fallback_text', models.TextField(blank=True, verbose_name='Текст-заглушка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('ad_type', models.CharField(choices=[('widget', 'Widget'), ('banner', 'Баннер'), ('text', 'Текстовая ссылка')], max_length=20, verbose_name='Тип')),
                ('widget_code', models.TextField(blank=True, verbose_name='Код виджета (iframe/script)')),
                ('widget_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина виджета')),
                ('widget_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота виджета')),
                ('image', models.ImageField(blank=True, upload_to='ads/banners/', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Текст ссылки')),
                ('intro_text', models.CharField(blank=True, help_text="Текст перед объявлением: 'Лучшие отели Нячанга:'", max_length=500, verbose_name='Подводка')),
                ('slot_type', models.CharField(choices=[('widget_320x480', 'Widget 320x480'), ('widget_300x600', 'Widget 300x600'), ('banner_728x90', 'Banner 728x90'), ('banner_300x250', 'Banner 300x250'), ('text', 'Текстовая ссылка')], help_text='К какому слоту подходит это объявление', max_length=50, verbose_name='Тип слота')),
                ('is_permanent', models.BooleanField(default=True, verbose_name='Постоянный')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало показа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец показа')),
                ('priority', models.PositiveIntegerField(default=5, help_text='1-10. Чем выше, тем чаще показывается', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Приоритет')),
                ('max_impressions', models.PositiveIntegerField(blank=True, help_text='Null = без лимита', null=True, verbose_name='Макс. показов')),
                ('impressions_count', models.PositiveIntegerField(default=0, verbose_name='Показов')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Кликов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рекламное объявление',
                'verbose_name_plural': 'Рекламные объявления',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-слаг')),
                ('url', models.URLField(max_length=500, verbose_name='URL партнёра')),
                ('logo', models.ImageField(blank=True, upload_to='ads/partners/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=500, verbose_name='Referer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_clicks', to='blog.article', verbose_name='Статья')),
                ('ad_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.adunit', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Клики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adunit',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_units', to='ads.partner', verbose_name='Партнёр'),
        ),
    ]
