# Generated by Django 6.0.3 on 2026-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('blog', '0006_faq_is_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='adunit',
            name='target_categories',
            field=models.ManyToManyField(blank=True, help_text='Показывать только в статьях этих категорий', to='blog.category', verbose_name='Категории статей'),
        ),
    ]
