# Generated by Django 6.0.3 on 2026-03-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_add_target_categories'),
        ('blog', '0006_faq_is_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Укажите где вставить: before_h2, after_paragraph, end', max_length=50, verbose_name='Позиция в тексте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='ads.adunit', verbose_name='Объявление (null = автовыбор)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_placements', to='blog.article', verbose_name='Статья')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='ads.adslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Размещение в статье',
                'verbose_name_plural': 'Размещения в статьях',
                'ordering': ['article', 'order'],
                'unique_together': {('article', 'slot', 'position')},
            },
        ),
    ]
