# Generated by Django 6.0.3 on 2026-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_add_article_ad_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='slot_type',
            field=models.CharField(choices=[('widget_320x480', 'Widget 320x480'), ('widget_300x600', 'Widget 300x600'), ('banner_728x90', 'Banner 728x90'), ('banner_300x250', 'Banner 300x250'), ('banner_responsive', 'Баннер адаптивный'), ('text', 'Текстовая ссылка')], max_length=50, verbose_name='Тип слота'),
        ),
        migrations.AlterField(
            model_name='adunit',
            name='slot_type',
            field=models.CharField(choices=[('widget_320x480', 'Widget 320x480'), ('widget_300x600', 'Widget 300x600'), ('banner_728x90', 'Banner 728x90'), ('banner_300x250', 'Banner 300x250'), ('banner_responsive', 'Баннер адаптивный'), ('text', 'Текстовая ссылка')], help_text='К какому слоту подходит это объявление', max_length=50, verbose_name='Тип слота'),
        ),
    ]
