# Generated by Django 6.0.3 on 2026-03-28 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_add_banner_responsive_slot_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adslot',
            options={'ordering': ['page_type', 'order', 'name'], 'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.RemoveField(
            model_name='adslot',
            name='slot_type',
        ),
        migrations.RemoveField(
            model_name='adunit',
            name='slot_type',
        ),
        migrations.AddField(
            model_name='adslot',
            name='page_type',
            field=models.CharField(choices=[('article', 'Статья'), ('news', 'Новость'), ('product', 'Продукт')], default='article', max_length=20, verbose_name='Тип страницы'),
        ),
        migrations.AddField(
            model_name='adslot',
            name='position',
            field=models.CharField(default='middle', help_text='before_h2, middle, before_faq, end (для статей) или top, middle, bottom', max_length=50, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='html_code',
            field=models.TextField(blank=True, help_text='Код для динамических баннеров (Google Ads, Yandex, и т.д.)', verbose_name='HTML/JS код'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_units', to='ads.adslot', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='adunit',
            name='ad_type',
            field=models.CharField(choices=[('widget', 'Widget'), ('banner', 'Баннер (статичный)'), ('html', 'HTML/JS код'), ('text', 'Текстовая ссылка')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='articleadplacement',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='ads.adslot', verbose_name='Позиция'),
        ),
    ]
