# Generated by Django 6.0.3 on 2026-03-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_refactor_slots_and_add_html'),
        ('blog', '0006_faq_is_auto'),
        ('news', '0007_add_tag_to_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='adunit',
            name='target_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_ads', to='blog.article', verbose_name='Конкретная статья'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='target_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_ads', to='news.newsitem', verbose_name='Конкретная новость'),
        ),
        migrations.DeleteModel(
            name='ArticleAdPlacement',
        ),
    ]
