# Generated by Django 6.0.3 on 2026-03-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='facebook_url',
        ),
        migrations.AddField(
            model_name='vendor',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
    ]
