# Generated by Django 6.0.3 on 2026-03-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_rename_facebook_to_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description_md',
            field=models.TextField(blank=True, help_text='Редактируйте здесь. HTML в поле «description» генерируется автоматически при сохранении.', verbose_name='Описание (Markdown)'),
        ),
    ]
