# Generated by Django 6.0.3 on 2026-03-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_add_description_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='map_url',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
