# Generated by Django 6.0.3 on 2026-03-27 22:23

from django.db import migrations


def fix_blog_soveti_redirect(apps, schema_editor):
    try:
        Redirect = apps.get_model('redirects', 'Redirect')
        Redirect.objects.filter(old_path='/blog-soveti-history/').update(new_path='/#tags')
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('redirects', '0002_alter_redirect_new_path_help_text'),
    ]

    operations = [
        migrations.RunPython(fix_blog_soveti_redirect, migrations.RunPython.noop),
    ]
