# Generated by Django 6.0.3 on 2026-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_fix_blog_soveti_redirect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='content_md',
            field=models.TextField(blank=True, help_text='Markdown версия контента. Приоритетнее чем HTML.', verbose_name='Контент (Markdown)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
